package:
  name: envvar-pythonpath-null
  version: 0.1.0

build:
  number: 1

test:
  commands:
    - test -z $PYTHONPATH           # [unix]
    - if defined PYTHONPATH exit 1  # [win]

about:
  home: https://github.com/mfansler/envvar-pythonpath-null
  license: CC0-1.0
  summary: "Unset 'PYTHONPATH' on environment activation."
  description: |
    This package unsets the environment variable 'PYTHONPATH'
    when the Conda environment is activated. This prevents the Python
    from loading modules from any directories this variable provides,
    effectively insulating the Conda environment from user-level
    packages.

extra:
  maintainers:
    - mfansler
